language: python
python:
  - 2.7
  - 3.2
  - 3.5

services:
  - docker

install:
  - docker build -t rskn/nodejs .
  - docker run -d --name rskn/nodejs rskn/nodejs

script:
  - docker ps | grep -q rskn/nodejs
